// <auto-generated />
namespace Ecommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changement_des_Index_de_Seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changement_des_Index_de_Seed));
        
        string IMigrationMetadata.Id
        {
            get { return "201904021026217_Changement_des_Index_de_Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
